// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma @prisma/adapter-better-sqlite3 better-sqlite3
import "dotenv/config";
import path from "node:path";
import { defineConfig } from "prisma/config";
import { PrismaLibSQL } from "@prisma/adapter-libsql";

// For local SQLite, we use the libsql adapter
const adapter = new PrismaLibSQL({
  url: `file:${path.resolve(__dirname, process.env["DATABASE_URL"]?.replace("file:", "") || "dev.db")}`,
});

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    adapter,
  },
});
